name: Sawyer shirt holsters
favicon: null
layout_spectrum: 0.4229616401717067
typography_spectrum: 0.04747607558965683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0021406582091003656
  lightness: 0.5293083526194096
  saturation: 0.2232382872607559
  rhythmicContrast: 0.09221684536896646
purpose: []
